<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\ChatSystem.Application\ChatSystem.Application.csproj"/>
        <ProjectReference Include="..\ChatSystem.Infrastructure\ChatSystem.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.7"/>
        <PackageReference Include="System.Reactive" Version="6.0.1"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
